version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: code.technokrat.ch
    ports:
      - "2222:22"
    volumes:
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/config:/etc/gitlab
      - /storage/gitlab_registry:/var/opt/gitlab/gitlab-rails/shared/registry
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab_config
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.gitlab.rule=Host(`code.technokrat.ch`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=le
      - traefik.http.services.gitlab.loadbalancer.server.port=80
  
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4

configs:
  gitlab_config:
    external: true
secrets:
  gitlab_root_password:
    external: true

